import { createSlice } from "@reduxjs/toolkit";

// Create a slice for managing user data
const userSlice = createSlice({
  // Name of the slice
  name: "user",

  // Initial state of the user slice
  initialState: {
    userName: "",
    monthlyBudget: "",
    categoricalBudget: {
      food: "",
      travel: "",
      entertainment: "",
      others: "",
    },
    activeFilter: "all",
  },

  // Reducers to update different parts of the user state
  reducers: {
    // Reducer to update user's name
    updateUserName: (state, action) => {
      state.userName = action.payload;
    },

    // Reducer to update user's monthly budget
    updateMonthlyBudget: (state, action) => {
      state.monthlyBudget = action.payload;
    },

    // Reducer to update user's categorical budget
    updateCategoricalBudget: (state, action) => {
      state.categoricalBudget = {
        ...state.categoricalBudget,
        ...action.payload,
      };

      return state;
    },

    // Reducer to update active filter
    updateActiveFilter: (state, action) => {
      state.activeFilter = action.payload;
    },

    resetAllBudget: (state) => {
      state.userName = "";
      state.monthlyBudget = "";
      state.categoricalBudget = {
        food: "",
        travel: "",
        entertainment: "",
      };
      state.activeFilter = "all";
    },
  },
});

// Extract action creators from the slice
export const {
  updateUserName,
  updateMonthlyBudget,
  updateCategoricalBudget,
  updateActiveFilter,
  resetAllBudget,
} = userSlice.actions;

// Export the reducer function generated by createSlice
export default userSlice.reducer;
